services:
  - type: web
    name: boardmate
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn onlinequiz.wsgi:application"
    pythonVersion: 3.11
